### ISSUE TITLE
Provide `openBabel` 

### ISSUE THREAD

**Issue by martin-g** [bio-arm/bio-arm.github.io#1]
openEuler 22.03 does not provide an OS package for openbabel-devel (https://github.com/Bioconductor/BBS/blob/af1f643c3ed4ab6fb5f7d450b801f43812a35b88/Ubuntu-files/22.04/apt_bioc.txt#L18)

This leads to a build failure for [ChemmineOB](https://bio-arm.github.io/openeuler-0526/report/ChemmineOB/kunpeng2-install.html) package

**Comment by Yikun** [comment]
Great! It's a good start! Would you mind also write a simple notes to show how to validate INSTALL/BUILD/CHECK stage for a bioconductor package mannully?

**Comment by martin-g** [comment]
I will add this information in the README!

**Comment by martin-g** [comment]
openBabel rpm is available at https://eur.openeuler.openatom.cn/coprs/yikun/bioconductor/
