### ISSUE TITLE
Provide `OpenCL` 

### ISSUE THREAD

**Issue by martin-g** [bio-arm/bio-arm.github.io#2]
openEuler does not provide a package similar to [ocl-icd-opencl-dev](https://github.com/Bioconductor/BBS/blob/af1f643c3ed4ab6fb5f7d450b801f43812a35b88/Ubuntu-files/22.04/apt_bioc.txt#LL21C1-L21C20)

This leads to build failures like https://bio-arm.github.io/openeuler-0526/report/gpuMagic/kunpeng2-install.html

**Comment by XingYuuuuu** [comment]
hi,what version of libOpenCL1 is needed here? I have another question. How is the version that lacks the dependency package determined? Thank you.

**Comment by martin-g** [comment]
Bioconductor project uses Ubuntu 22.04 for its testing on Linux x86_64 and Ubuntu 22.04 provides version 2.2.14-3:
```
# apt show ocl-icd-opencl-dev
Package: ocl-icd-opencl-dev
Version: 2.2.14-3
Architecture: amd64
Installed: no
Priority: extra
Essential: no
Section: universe/libdevel
Source: ocl-icd
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian OpenCL Maintainers <pkg-opencl-devel@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 24 KB
Provides: opencl-dev
Depends: opencl-c-headers | opencl-headers, opencl-clhpp-headers | opencl-headers, ocl-icd-libopencl1 (= 2.2.14-3)
Recommends: libgl1-mesa-dev | libgl-dev
Replaces: 
  amd-libopencl1
  nvidia-libopencl1
  ocl-icd-libopencl1
  ocl-icd-libopencl1
  ocl-icd-opencl-dev
  opencl-dev
  opencl-dev
Conflicts: opencl-dev
Breaks: amd-libopencl1 (< 1:13.4-4~), nvidia-libopencl1 (< 305~), ocl-icd-libopencl1 (< 2.1.3-5~), ocl-icd-opencl-dev (!= 2.2.14-3)
Homepage: https://github.com/OCL-dev/ocl-icd
Download-Size: 2 KB
APT-Sources: https://mirrors.tuxedocomputers.com/ubuntu/ jammy/universe amd64 Packages
Description: OpenCL development files
 OpenCL (Open Computing Language) is a multivendor open standard for
 general-purpose parallel programming of heterogeneous systems that include
 CPUs, GPUs and other processors.
 .
 This package provides the development files: headers and libraries.
 .
 It also ensures that the ocl-icd ICD loader is installed so its additional
 features (compared to the OpenCL norm) can be used: .pc file, ability to
 select an ICD without root privilege, etc.
```



> How is the version that lacks the dependency package determined?

I don't understand your question. Please re-phrase it.

**Comment by XingYuuuuu** [comment]
I'm sorry, I mean, what's the basis for judging the source package version?

**Comment by martin-g** [comment]
I am not aware of any conditions in choosing the version.

The Bioconductor project just depends on whatever version is available in the Ubuntu repositories.
Here are the files for Ubuntu 20.04 and 22.04:
- https://github.com/Bioconductor/BBS/blob/f87de6f9b752c653e2b52914635cca4c4deb78c9/Ubuntu-files/20.04/apt_bioc.txt#L21
- https://github.com/Bioconductor/BBS/blob/f87de6f9b752c653e2b52914635cca4c4deb78c9/Ubuntu-files/22.04/apt_bioc.txt#L21
