### ISSUE TITLE
Provide gdal-devel

### ISSUE THREAD

**Issue by martin-g** [bio-arm/bio-arm.github.io#8]
openEuler OS does not provide `gdal-devel` package.
It is needed by Bioconductor `apt-cran.txt` - https://github.com/Bioconductor/BBS/blob/f87de6f9b752c653e2b52914635cca4c4deb78c9/Ubuntu-files/22.04/apt_cran.txt#L19

Currently we build it from [source ](https://github.com/bio-arm/dockerfiles/blob/main/scripts/setup-gdal.sh) but it is slow to build and Github Actions often times out during the execution of `setup-gdal.sh`. It would be good to create a `.rpm` for it soon!

**Comment by Yikun** [comment]
Please address this issue with high priority: @XingYuuuuu

**Comment by Yikun** [comment]
https://src.fedoraproject.org/rpms/gdal and https://github.com/bio-arm/dockerfiles/blob/main/scripts/setup-gdal.sh might a good reference

**Comment by martin-g** [comment]
The Github Actions workflow often fails during the build of GDAL with errors like:
- [Received request to deprovision: The request was cancelled by the remote provider.](https://github.com/bio-arm/dockerfiles/actions/runs/5288260659)
- [The hosted runner encountered an error while running your job. (Error Type: Disconnect).](https://github.com/bio-arm/dockerfiles/actions/runs/5287051079)

But you can build the Docker image locally as a workaround: `docker build -t bioc-oe .`

**Comment by Yikun** [comment]
@martin-g Could you also push the image to ghcr or dockerhub, this might also help!

**Comment by martin-g** [comment]
There is some problem with the aarch64 version of docker.io/openeuler/openeuler:22.03-lts-sp1
I can't use `sudo` in it.
First it failed with `Permissions denied` because its permissions were `---s--x--x` instead of `-rwsr-xr-x`.
I manually set the correct ones but now it fails with `sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?`
It seems I will need to push an `x86_64` from my dev machine and an `aarch64` from a VM ...

**Comment by Yikun** [comment]
Is the x86 version of `docker.io/openeuler/openeuler:22.03-lts-sp1` ok?

**Comment by martin-g** [comment]
Yes, it seems so!
I was able to upload a x86_64 image at https://github.com/users/martin-g/packages/container/package/bioc-openeuler-22.03
But the build on my ARM64 VM failed with other kind of problems... I will investigate it now!

**Comment by martin-g** [comment]
gdal rpm is available at https://eur.openeuler.openatom.cn/coprs/yikun/bioconductor/

**Comment by martin-g** [comment]
The latest Github CI build passed in building the packages which still don't have rpms but failed with `no space left on device`:
https://github.com/bio-arm/dockerfiles/actions/runs/5376109096/jobs/9752817614
