### ISSUE TITLE
RPM need to be installed

### ISSUE THREAD

**Issue by Yikun** [bio-arm/bio-arm.github.io#9]

**Comment by Yikun** [comment]
1. https://bioconductor.org/checkResults/3.18/bioc-LATEST/flowPloidy/kunpeng2-buildsrc.html

! Package fontenc Error: Encoding file `ly1enc.def' not found.

https://search.oepkgs.net/list?s=ly1enc.def&searchType=files&exactSearch=exact

dnf install texlive-ly1

**Comment by martin-g** [comment]
The package is installed on `kunpeng2` and [added](https://github.com/bio-arm/bio-arm.github.io/issues/9) to dnf_cran.sh for the Docker [image](https://github.com/bio-arm/dockerfiles/blob/4112310efec090dfd807c2f9415359b1745e82fc/scripts/setup-BBS.sh#L13).
